#!/usr/bin/env bash

set -e
set -o errexit
set -o nounset

if [ ! -n "$BUILDKITE" ]; then
    echo "This script will only work within the buildkite environment"
    exit 1
fi

if [ ! -n "$PACKAGECLOUD_TOKEN" ]; then
    echo "PACKAGECLOUD_TOKEN must be set"
    exit 1
fi

# default packagecloud repo
: "${PACKAGECLOUD_REPOSITORY:=digitalocean-eng/test-packages}"

# packagecloud uploader
uploader=quay.io/digitalocean/package_builder_uploader

echo "--- Downloading artifacts from build phase"
[ ! -d packages ] && mkdir packages
buildkite-agent artifact download "*" packages/

echo "--- Uploading packages to ${PACKAGECLOUD_REPOSITORY} respository"
docker run --rm -t -e "PACKAGECLOUD_TOKEN=${PACKAGECLOUD_TOKEN}" -v "$(pwd)/packages":/packages ${uploader} bash -c "package_cloud push ${PACKAGECLOUD_REPOSITORY}/ubuntu/trusty /packages/**/*.deb"
